apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cert-manager-subscription
  namespace: cert-manager
spec:
  channel: cert-manager/cert-manager-channel
  placement:
    placementRef:
      name: prod-clusters
      kind: PlacementRule
      apiGroup: apps.open-cluster-management.io
